### ISSUE TITLE
Meta: Epidemic time series data

### ISSUE THREAD

**Issue by zsusswein** [epistorm/rt-collabathon-2024#4]
- [ ] Basic epidemic time series (already exists in repo)
- [ ] Remove random report dates: low, medium, high
- [ ] Remove random reference dates: low, medium, high
- [ ] Noise: low medium high (k = 15, 10, 5)?
- [ ] Right truncation: none, moderate, high?
